/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alexa_domain;

import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Collections;
import java.util.List;

import java.net.URL;
import java.net.MalformedURLException;
import com.google.common.net.InternetDomainName;

public class App {
  private int unknownTopPrivateDomainCount = 0;

  public String topPrivateDomain(String host) {
    String topPrivateDomain = null;

    try {
      topPrivateDomain = InternetDomainName.from(host).topPrivateDomain().toString();
    } catch (java.lang.IllegalStateException e) {
      e.printStackTrace();
      System.err.println(host);
      unknownTopPrivateDomainCount++;
    } catch (java.lang.IllegalArgumentException e) {
      e.printStackTrace();
      System.err.println(host);
      unknownTopPrivateDomainCount++;
    };

    return topPrivateDomain;
  }

  public void run(BufferedReader alexabuf, BufferedReader urlbuf) throws IOException {
    HashMap<String, Integer> rank = new HashMap();
    String line = null;
    while ((line = alexabuf.readLine()) != null) {
      String[] row = line.split(",");
      String tld = topPrivateDomain(row[1]);
      if (null == tld) {
        continue;
      }
      rank.put(tld, Integer.parseInt(row[0]));
    }

    while ((line = urlbuf.readLine()) != null) {
      String[] row = line.split(",");
      String tld = topPrivateDomain(row[1]);
      Integer score = new Integer(0);
      if (null != tld && null != rank.get(tld)) {
        score = Integer.valueOf(1000001) - rank.get(tld);
      }
      System.out.printf("%s %d\n", row[0], score);
    }
  }

  public static void main(String[] args) throws IOException {
    FileReader f0 = new FileReader(args[0]);
    BufferedReader buf0 = new BufferedReader(f0);
    FileReader f1 = new FileReader(args[1]);
    BufferedReader buf1 = new BufferedReader(f1);

    new App().run(buf0, buf1);
  }
}
